apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: simple-python-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}