replicaCount: 2

image:
  repository: your-dockerhub-username/simple-python-app
  tag: 2046480c41c658f7f14cc5f5ae589052af1d391d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

containerPort: 5000