# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: simple-app
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: simple-app
#   template:
#     metadata:
#       labels:
#         app: simple-app
#     spec:
#       containers:
#         - name: simple-app
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - containerPort: {{ .Values.containerPort }}
#           livenessProbe:
#             httpGet:
#               path: /health/live
#               port: {{ .Values.containerPort }}
#             initialDelaySeconds: 10
#             periodSeconds: 10
#             timeoutSeconds: 2
#             failureThreshold: 3

#           readinessProbe:
#             httpGet:
#               path: /health/ready
#               port: {{ .Values.containerPort }}
#             initialDelaySeconds: 5
#             periodSeconds: 5
#             timeoutSeconds: 2
#             failureThreshold: 3

#           startupProbe:
#             httpGet:
#               path: /health/live
#               port: {{ .Values.containerPort }}
#             initialDelaySeconds: 0
#             periodSeconds: 5
#             timeoutSeconds: 2
#             failureThreshold: 30