replicaCount: 2

image:
  repository: ksreenath2027/simple-app
  tag: 6167e0c
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5002

containerPort: 5002
ingress:
  enabled: true
  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

  tls: []